// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
@import CoreGraphics;
@import CoreData;
#endif

#import <SidestepSDK/SidestepSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

SWIFT_CLASS("_TtC11SidestepSDK10APIManager")
@interface APIManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL isInitializedSharedManager;)
+ (BOOL)isInitializedSharedManager;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) APIManager * _Nullable sharedManager;)
+ (APIManager * _Nullable)sharedManager;
+ (void)setSharedManager:(APIManager * _Nullable)value;
@property (nonatomic, readonly, copy) NSString * _Nonnull baseUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end

@class NSNumber;
@class NSDictionary;
@class UpdateOrderParams;

@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
+ (void)getShows:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getShows:(NSNumber * _Nonnull)artistId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)objcGetShowProductVariants:(NSArray<NSNumber *> * _Nonnull)showProductIds success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)objcGetShowProductsForShowWithId:(NSNumber * _Nonnull)showId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getShowProductsForProductWithId:(NSNumber * _Nonnull)productId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getProductVariants:(NSArray<NSNumber *> * _Nonnull)productIds success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getProduct:(NSNumber * _Nonnull)productId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getProducts:(NSArray<NSNumber *> * _Nonnull)productIds success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getArtists:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getOrders:(NSArray<NSNumber *> * _Nonnull)ids orderToken:(NSString * _Nullable)orderToken success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getOrders:(NSNumber * _Nonnull)userId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)updateDeliveryAddress:(NSNumber * _Nonnull)orderId addressInfo:(NSDictionary<NSString *, id> * _Nonnull)addressInfo success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)createDeliveryAddress:(NSNumber * _Nonnull)orderId addressInfo:(NSDictionary<NSString *, id> * _Nonnull)addressInfo success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)recoverPassword:(NSString * _Nonnull)email success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)updatePassword:(NSString * _Nonnull)password token:(NSString * _Nonnull)token success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getCartOrderForCurrentUserObjc:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getShow:(NSNumber * _Nonnull)showId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)placeOrder:(NSNumber * _Nonnull)orderId cardId:(NSNumber * _Nullable)cardId chargeToken:(NSString * _Nullable)chargeToken dateOfBirth:(NSDate * _Nullable)dateOfBirth success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getTokenObjc:(NSString * _Nonnull)email password:(NSString * _Nonnull)password success:(void (^ _Nullable)(NSDictionary * _Nullable))success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getTokenObjc:(NSString * _Nonnull)fbToken email:(NSString * _Nullable)email success:(void (^ _Nullable)(NSDictionary * _Nullable))success failure:(FailureObjcBlock _Nullable)failure;
+ (void)createUser:(NSString * _Nonnull)firstName lastName:(NSString * _Nonnull)lastName email:(NSString * _Nonnull)email password:(NSString * _Nonnull)password success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getCurrentUser:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)updateOrder:(NSNumber * _Nonnull)orderId params:(UpdateOrderParams * _Nullable)params success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)downloadPassbookFile:(NSNumber * _Nonnull)orderId orderToken:(NSString * _Nullable)orderToken success:(void (^ _Nullable)(NSData * _Nullable))success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getOrder:(NSNumber * _Nonnull)orderId orderToken:(NSString * _Nullable)orderToken success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getAdvanceSheets:(NSArray<NSNumber *> * _Nonnull)showIds success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getCard:(NSNumber * _Nonnull)cardId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
@end


SWIFT_CLASS("_TtC11SidestepSDK19APIManagerConstants")
@interface APIManagerConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerFirstNameKey;)
+ (NSString * _Nonnull)kAPIManagerFirstNameKey;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerLastNameKey;)
+ (NSString * _Nonnull)kAPIManagerLastNameKey;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerAddress1Key;)
+ (NSString * _Nonnull)kAPIManagerAddress1Key;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerAddress2Key;)
+ (NSString * _Nonnull)kAPIManagerAddress2Key;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerCityKey;)
+ (NSString * _Nonnull)kAPIManagerCityKey;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerRegionKey;)
+ (NSString * _Nonnull)kAPIManagerRegionKey;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerZipKey;)
+ (NSString * _Nonnull)kAPIManagerZipKey;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerCountryKey;)
+ (NSString * _Nonnull)kAPIManagerCountryKey;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerCountryCodeKey;)
+ (NSString * _Nonnull)kAPIManagerCountryCodeKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIVisualEffect;
@class NSCoder;

SWIFT_CLASS("_TtC11SidestepSDK10BluredView")
@interface BluredView : UIVisualEffectView
- (nonnull instancetype)initWithEffect:(UIVisualEffect * _Nullable)effect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)switchToTransparentState;
- (void)switchToBluredState;
@end

@class UITableView;

SWIFT_CLASS("_TtC11SidestepSDK18AbstractPickerView")
@interface AbstractPickerView : BluredView
@property (nonatomic, strong) IBOutlet UITableView * _Null_unspecified tableView;
+ (AbstractPickerView * _Nonnull)create;
- (void)showBottomButtonWithTitle:(NSString * _Nonnull)title target:(id _Nonnull)target action:(SEL _Nonnull)action;
@property (nonatomic, readonly) CGFloat bottomSectionHeight;
- (void)updateConstraints;
- (nonnull instancetype)initWithEffect:(UIVisualEffect * _Nullable)effect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC11SidestepSDK7Address")
@interface Address : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable addressId;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable address1;
@property (nonatomic, copy) NSString * _Nullable address2;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable region;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, strong) NSSet * _Nullable orders;
- (NSString * _Nonnull)addressString;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Artist;
@class Show;

SWIFT_CLASS("_TtC11SidestepSDK12AdvanceSheet")
@interface AdvanceSheet : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable advanceSheetId;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, strong) NSNumber * _Nullable servicedBySidestep;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) Show * _Nullable show;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class UIAlertController;

SWIFT_CLASS("_TtC11SidestepSDK24AlertControllerPresenter")
@interface AlertControllerPresenter : NSObject
+ (void)presentAlert:(UIAlertController * _Nonnull)alertController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSOrderedSet;

SWIFT_CLASS("_TtC11SidestepSDK6Artist")
@interface Artist : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, strong) NSNumber * _Nullable order;
@property (nonatomic, strong) NSNumber * _Nullable stockId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable slug;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, strong) NSNumber * _Nullable published;
@property (nonatomic, strong) NSNumber * _Nullable isDeliveryAvailable;
@property (nonatomic, strong) NSNumber * _Nullable stripeConnectionId;
@property (nonatomic, strong) NSOrderedSet * _Nullable products;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
@property (nonatomic, strong) NSOrderedSet * _Nullable advanceSheets;
@property (nonatomic, strong) NSOrderedSet * _Nullable tours;
@property (nonatomic, strong) NSOrderedSet * _Nullable orders;
@property (nonatomic, strong) NSNumber * _Nullable localAttributeIsArtistMissedInResponse;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK21BluredModalController_")
@protocol BluredModalController
@property (nonatomic, readonly, strong) BluredView * _Nonnull bluredView;
@end


@class User;

SWIFT_CLASS("_TtC11SidestepSDK4Card")
@interface Card : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable cardId;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable last4;
@property (nonatomic, strong) User * _Nullable user;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@protocol CartFlowConfiguratorDelegate;
@class FlowControllerSettings;
@class UIViewController;

SWIFT_PROTOCOL("_TtP11SidestepSDK28CartFlowConfiguratorProtocol_")
@protocol CartFlowConfiguratorProtocol <NSObject>
@property (nonatomic, strong) id <CartFlowConfiguratorDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSArray<FlowControllerSettings *> * _Nonnull flowControllers;
- (void)runPreAction:(UIViewController * _Nonnull)fromController completion:(void (^ _Nonnull)(BOOL))completion;
@end


SWIFT_CLASS("_TtC11SidestepSDK5Error")
@interface Error : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable errors;
@property (nonatomic, readonly, copy) NSString * _Nullable error;
@property (nonatomic, readonly, copy) NSDate * _Nonnull datetime;
- (NSString * _Nullable)baseError;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@protocol ErrorHandlerSupportWorker;

SWIFT_CLASS("_TtC11SidestepSDK12ErrorHandler")
@interface ErrorHandler : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ErrorHandler * _Nonnull sharedInstance;)
+ (ErrorHandler * _Nonnull)sharedInstance;
- (nonnull instancetype)initWithSuportWorker:(id <ErrorHandlerSupportWorker> _Nullable)suportWorker OBJC_DESIGNATED_INITIALIZER;
- (void)displayError:(Error * _Nullable)error;
- (void)supportButtonTap:(NSString * _Nullable)subject;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK25ErrorHandlerSupportWorker_")
@protocol ErrorHandlerSupportWorker
- (BOOL)shouldAddSupportButton:(Error * _Nullable)error;
- (void)supportButtonTap:(NSString * _Nullable)subject;
@end

@protocol NSFetchedResultsControllerDelegate;

SWIFT_CLASS("_TtC11SidestepSDK10FRCFactory")
@interface FRCFactory : NSObject
// 'createPickUpOrdersForOrdersController(_:delegate:)' below
// 'createDeliveryOrdersForOrdersController(_:delegate:)' below
// 'createCartOrderForCartManager(_:)' below
// 'createPlacedOrderForOrderCompletionController(_:)' below
// 'createOrderMonitorForOrderConfirmationController(_:)' below
// 'createOrderItemsMonitorForOrderConfirmationController(_:delegate:)' below
// 'createOrderMonitorForCartTableViewManager(_:)' below
+ (NSFetchedResultsController<Artist *> * _Nonnull)createPublishedArtistsMonitorForArtistsController:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
// 'createOrderMonitorForCartController(_:)' below
// 'createOrderItemsMonitorForCartController(_:delegate:)' below
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SSCheckoutFlowProtocol;

SWIFT_CLASS("_TtC11SidestepSDK22FlowControllerSettings")
@interface FlowControllerSettings : NSObject
@property (nonatomic, readonly) BOOL showStep;
@property (nonatomic, readonly, copy) id <SSCheckoutFlowProtocol> _Nonnull (^ _Nonnull builderBlock)(void);
- (nonnull instancetype)initWithBuilderBlock:(id <SSCheckoutFlowProtocol> _Nonnull (^ _Nonnull)(void))builderBlock showStep:(BOOL)showStep OBJC_DESIGNATED_INITIALIZER;
+ (FlowControllerSettings * _Nonnull)create:(id <SSCheckoutFlowProtocol> _Nonnull (^ _Nonnull)(void))builderBlock showStep:(BOOL)showStep;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSDateFormatter;

SWIFT_CLASS("_TtC11SidestepSDK9Formatter")
@interface Formatter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDateFormatter * _Nonnull jsonDateFormatter;)
+ (NSDateFormatter * _Nonnull)jsonDateFormatter;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDateFormatter * _Nonnull jsonDateTimeFormatter;)
+ (NSDateFormatter * _Nonnull)jsonDateTimeFormatter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSManagedObject (SWIFT_EXTENSION(SidestepSDK))
@end


@interface NSObject (SWIFT_EXTENSION(SidestepSDK))
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK18NavigationDelegate_")
@protocol NavigationDelegate <NSObject>
- (void)showCart;
- (void)showHomeController;
@end


SWIFT_CLASS("_TtC11SidestepSDK5Order")
@interface Order : NSManagedObject
@property (nonatomic, copy) NSString * _Nullable confirmationCode;
@property (nonatomic, strong) NSNumber * _Nullable orderId;
@property (nonatomic, strong) NSNumber * _Nullable subtotal;
@property (nonatomic, strong) NSNumber * _Nullable fee;
@property (nonatomic, strong) NSNumber * _Nullable total;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, strong) NSNumber * _Nullable shippingFee;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable orderToken;
@property (nonatomic, copy) NSString * _Nullable deliveryMethod;
@property (nonatomic, strong) NSNumber * _Nullable shippingAddressId;
@property (nonatomic, strong) NSOrderedSet * _Nullable orderItems;
@property (nonatomic, strong) Show * _Nullable show;
@property (nonatomic, strong) Address * _Nullable shippingAddress;
@property (nonatomic, strong) User * _Nullable user;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic) id _Nullable orderItemIds;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable refundState;
@property (nonatomic, copy) NSDate * _Nullable refundedAt;
@property (nonatomic, copy) NSString * _Nullable trackingCode;
@property (nonatomic, copy) NSString * _Nullable trackingUrl;
@property (nonatomic, copy) NSString * _Nullable orderTextStatus;
@property (nonatomic, strong) NSNumber * _Nullable deliveryState;
@property (nonatomic, copy) NSString * _Nullable referrer;
+ (NSArray<Order *> * _Nullable)getCartOrders;
+ (Order * _Nullable)getOrder:(NSString * _Nonnull)orderToken;
@property (nonatomic, readonly) BOOL isPickupOrder;
@property (nonatomic, readonly) BOOL isDeliveryOrder;
@property (nonatomic, readonly) BOOL isCartOrder;
@property (nonatomic, readonly) BOOL isRefunded;
- (void)unlinkShowAndSave;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class OrderItem;
@class ProductVariant;
@protocol OrderCartWorkerDelegate;

SWIFT_CLASS("_TtC11SidestepSDK15OrderCartWorker")
@interface OrderCartWorker : NSObject
@property (nonatomic, weak) id <OrderCartWorkerDelegate> _Nullable delegate;
- (void)updateOrderItemObjc:(OrderItem * _Nonnull)orderItem newQuantity:(NSNumber * _Nullable)newQuantity newProductVariantId:(NSNumber * _Nullable)newProductVariantId successBlock:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
- (void)deleteOrderItemObjc:(OrderItem * _Nonnull)orderItem successBlock:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
- (void)addOrderItemToCartForDelivery:(ProductVariant * _Nonnull)productVariant;
- (void)addOrderItemToCartForPickUp:(ProductVariant * _Nonnull)productVariant showId:(NSNumber * _Nonnull)showId;
- (void)addOrderItemWithNotSelectedPickUpMethod:(ProductVariant * _Nonnull)productVariant;
- (BOOL)needToChangePickUpMethod:(Order * _Nonnull)cartOrder isDelivery:(BOOL)isDelivery showId:(NSNumber * _Nullable)_showId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSHTTPURLResponse;

SWIFT_PROTOCOL("_TtP11SidestepSDK23OrderCartWorkerDelegate_")
@protocol OrderCartWorkerDelegate <NSObject>
@optional
- (void)workerWillStartLoadingData:(OrderCartWorker * _Nonnull)worker;
- (void)workerDidFinishLoadingData:(OrderCartWorker * _Nonnull)worker;
- (void)worker:(OrderCartWorker * _Nonnull)worker getError:(NSHTTPURLResponse * _Nullable)response error:(Error * _Nullable)error;
- (void)didEndAddingOrderItemToCart;
@end

typedef SWIFT_ENUM(NSInteger, OrderDeliveryMethod) {
  OrderDeliveryMethodPickup = 0,
  OrderDeliveryMethodShipToAddress = 1,
  OrderDeliveryMethodNotDefined = 2,
};

@class NSPredicate;

SWIFT_CLASS("_TtC11SidestepSDK9OrderItem")
@interface OrderItem : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable orderItemId;
@property (nonatomic, strong) NSNumber * _Nullable price;
@property (nonatomic, strong) NSNumber * _Nullable fee;
@property (nonatomic, strong) NSNumber * _Nullable applicationFee;
@property (nonatomic, strong) NSNumber * _Nullable quantity;
@property (nonatomic, strong) NSNumber * _Nullable state;
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, strong) NSNumber * _Nullable orderId;
@property (nonatomic, strong) NSNumber * _Nullable available;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable artistTitle;
@property (nonatomic, copy) NSString * _Nullable priceType;
@property (nonatomic, strong) ProductVariant * _Nullable productVariant;
@property (nonatomic, strong) Order * _Nullable order;
+ (NSPredicate * _Nonnull)orphanedOrderItemsOrInCartPredicate;
+ (OrderItem * _Nullable)getOrderItem:(NSNumber * _Nonnull)orderItemId;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Tour;

SWIFT_CLASS("_TtC11SidestepSDK7Product")
@interface Product : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, strong) NSNumber * _Nullable price;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, strong) NSNumber * _Nullable tourId;
@property (nonatomic, strong) NSNumber * _Nullable published;
@property (nonatomic, strong) NSNumber * _Nullable productDeleted;
@property (nonatomic, strong) NSNumber * _Nullable exclusive;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable squareImage;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) Tour * _Nullable tour;
@property (nonatomic, copy) NSString * _Nullable productDescription;
@property (nonatomic, strong) NSOrderedSet * _Nullable productVariants;
@property (nonatomic, strong) NSNumber * _Nullable sortOrder;
@property (nonatomic, strong) NSNumber * _Nullable availableForPickup;
@property (nonatomic, strong) NSNumber * _Nullable availableForDelivery;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) NSOrderedSet * _Nullable showProducts;
@property (nonatomic, strong) NSNumber * _Nullable localAttributeIsProductMissedInResponse;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK13ProductCVCell")
@interface ProductCVCell : UICollectionViewCell
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull reuseId;)
+ (NSString * _Nonnull)reuseId;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)prepareForReuse;
- (void)setImageUrl:(NSURL * _Nullable)imageUrl price:(NSString * _Nullable)price indexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class ShowProduct;
@class UITableViewCell;
@protocol ProductDetailsControllerDelegate;
@class NSBundle;

SWIFT_CLASS("_TtC11SidestepSDK24ProductDetailsController")
@interface ProductDetailsController : UITableViewController <OrderCartWorkerDelegate, ProductDetailsOtherProductsCellDelegate>
@property (nonatomic, weak) id <ProductDetailsControllerDelegate> _Nullable delegate;
@property (nonatomic, readonly, strong) ShowProduct * _Nullable showProduct;
@property (nonatomic, readonly, strong) Product * _Nullable product;
@property (nonatomic, strong) ProductVariant * _Nullable selectedVariant;
@property (nonatomic, readonly, strong) OrderCartWorker * _Nonnull orderCartWorker;
@property (nonatomic, readonly) BOOL showSizesForDelivery;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)didSelectProduct:(Product * _Null_unspecified)product;
- (void)workerWillStartLoadingData:(OrderCartWorker * _Nonnull)worker;
- (void)workerDidFinishLoadingData:(OrderCartWorker * _Nonnull)worker;
- (void)worker:(OrderCartWorker * _Nonnull)worker getError:(NSHTTPURLResponse * _Nullable)response error:(Error * _Nullable)error;
- (void)didEndAddingOrderItemToCart;
- (void)didAddOrderItemToCart;
- (void)didAddOrderItemToCartAndNeensToOpenCart;
- (void)dismissResolveConflictsController:(void (^ _Nullable)(void))completion;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK32ProductDetailsControllerDelegate_")
@protocol ProductDetailsControllerDelegate <NSObject>
- (void)didSelectProductFromOtherItems:(Product * _Nonnull)product;
- (void)productDetailsControllerItemAdded;
- (void)productDetailsControllerNeedsToGoToCart;
@end

@class SSSize;

SWIFT_CLASS("_TtC11SidestepSDK14ProductVariant")
@interface ProductVariant : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, strong) NSNumber * _Nullable enabled;
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, strong) NSNumber * _Nullable sizeId;
@property (nonatomic, strong) Product * _Nullable product;
@property (nonatomic, strong) SSSize * _Nullable size;
@property (nonatomic, strong) NSSet * _Nullable showProductVariants;
@property (nonatomic, strong) NSNumber * _Nullable price;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK18ProductsController")
@interface ProductsController : UIViewController <ProductDetailsControllerDelegate, NSFetchedResultsControllerDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull toursSegments;
@property (nonatomic, readonly) NSInteger selectedTourIndex;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
- (void)didSelectTourAtIndex:(NSInteger)index;
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)didSelectProductFromOtherItems:(Product * _Nonnull)product;
- (void)productDetailsControllerItemAdded;
- (void)productDetailsControllerNeedsToGoToCart;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ProductsController (SWIFT_EXTENSION(SidestepSDK))
+ (void)preloadAvailableShowsForAtristId:(NSNumber * _Nonnull)artistId success:(void (^ _Nonnull)(void))success failureObjc:(FailureObjcBlock _Nullable)failureObjc;
@end

@class UIImage;

SWIFT_CLASS("_TtC11SidestepSDK15QRCodeGenerator")
@interface QRCodeGenerator : NSObject
+ (UIImage * _Nullable)generateQRCodeFromString:(NSString * _Nonnull)string size:(CGFloat)size;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK26ReplaceOrderItemController")
@interface ReplaceOrderItemController : ProductsController
@property (nonatomic, readonly) BOOL blockFloatedCartButton;
- (nonnull instancetype)initWithOrderItem:(OrderItem * _Nonnull)orderItem delegate:(id <NavigationDelegate> _Nonnull)delegate OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)setupNavigationBar;
- (ProductDetailsController * _Nullable)createProductDetailsControllerForProduct:(Product * _Nullable)product;
@property (nonatomic, readonly) BOOL hidePickUpMethodSection;
@end

@class UITextField;

SWIFT_CLASS("_TtC11SidestepSDK20SDKPaymentMethodView")
@interface SDKPaymentMethodView : UIView <UITextFieldDelegate>
+ (SDKPaymentMethodView * _Nonnull)create;
- (void)awakeFromNib;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK6SSSize")
@interface SSSize : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable sizeId;
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSNumber * _Nullable order;
@property (nonatomic, readonly) BOOL isOneSizeOrNoSize;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Venue;

SWIFT_CLASS("_TtC11SidestepSDK4Show")
@interface Show : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic) id _Nullable artistIds;
@property (nonatomic) id _Nullable tourIds;
@property (nonatomic, strong) NSNumber * _Nullable venueId;
@property (nonatomic, strong) NSNumber * _Nullable hidden;
@property (nonatomic, strong) NSNumber * _Nullable isAdvanceRequired;
@property (nonatomic, copy) NSDate * _Nullable showDatetime;
@property (nonatomic, strong) NSOrderedSet * _Nullable artists;
@property (nonatomic, strong) NSOrderedSet * _Nullable tours;
@property (nonatomic, strong) NSOrderedSet * _Nullable orders;
@property (nonatomic, strong) Venue * _Nullable venue;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, strong) NSOrderedSet * _Nullable advanceSheets;
@property (nonatomic, strong) NSOrderedSet * _Nullable showProducts;
+ (Show * _Nullable)showWithId:(NSNumber * _Nonnull)showId;
+ (NSArray<Show *> * _Nullable)pastShows;
+ (NSArray<Show *> * _Nullable)servicedShows;
+ (NSArray<Show *> * _Nullable)servicedShows:(NSArray<NSNumber *> * _Nonnull)artistIds;
@property (nonatomic, readonly) BOOL isPastShow;
@property (nonatomic, readonly) BOOL isScheduled;
@property (nonatomic, readonly) BOOL isRunning;
@property (nonatomic, readonly) BOOL isFinished;
@property (nonatomic, readonly) BOOL isCancelled;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateString;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateStringLongStyle;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateStringShortStyle;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateTimeString;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK11ShowProduct")
@interface ShowProduct : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable showProductId;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, strong) NSNumber * _Nullable availableForOrdering;
@property (nonatomic, strong) Show * _Nullable show;
@property (nonatomic, strong) Product * _Nullable product;
@property (nonatomic, strong) NSSet * _Nullable showProductVariants;
+ (ShowProduct * _Nullable)getShowProduct:(NSNumber * _Nonnull)showProductId;
+ (NSArray<ShowProduct *> * _Nullable)getShowProducts:(NSArray<NSNumber *> * _Nonnull)productIds showId:(NSNumber * _Nonnull)showId;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK18ShowProductVariant")
@interface ShowProductVariant : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable showProductVariantId;
@property (nonatomic, strong) ShowProduct * _Nullable showProduct;
@property (nonatomic, strong) ProductVariant * _Nullable productVariant;
@property (nonatomic, strong) NSNumber * _Nullable showProductId;
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, strong) NSNumber * _Nullable availableQuantity;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariants:(NSNumber * _Nonnull)showProductId;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariants:(NSNumber * _Nonnull)showId productId:(NSNumber * _Nonnull)productId;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariantsSortedBySize:(NSNumber * _Nonnull)showId productVariantIds:(NSArray<NSNumber *> * _Nonnull)productVariantIds;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariantsSortedBySize:(NSNumber * _Nonnull)showId productId:(NSNumber * _Nonnull)productId;
@property (nonatomic, readonly) BOOL isAvailable;
@property (nonatomic, readonly) BOOL isCanBeOrderd;
@property (nonatomic, readonly) BOOL isShouldCheckAvailableQuantity;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class UINavigationController;

SWIFT_CLASS("_TtC11SidestepSDK11SidestepSDK")
@interface SidestepSDK : NSObject
@property (nonatomic, copy) void (^ _Nullable closeBlock)(void);
- (nonnull instancetype)initWithArtistId:(NSInteger)artistId token:(NSString * _Nonnull)token allowsNativeApp:(BOOL)allowsNativeApp useTestingServer:(BOOL)useTestingServer OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, strong) UINavigationController * _Nullable navigationController;
- (void)needToPopController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11SidestepSDK4Tour")
@interface Tour : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable tourId;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIAlertController (SWIFT_EXTENSION(SidestepSDK))
- (nonnull instancetype)initWithOkButtonAndMessage:(NSString * _Nullable)message;
- (nonnull instancetype)initWithOkButtonAndTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message;
- (nonnull instancetype)initWithOkButtonAndTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message okHandler:(void (^ _Nullable)(void))okHandler;
@end


@interface UIImageView (SWIFT_EXTENSION(SidestepSDK))
- (void)bridge_af_setImageWithURL:(NSURL * _Nonnull)url;
- (void)bridge_af_setImageWithURL:(NSURL * _Nonnull)url completion:(void (^ _Nullable)(UIImage * _Nullable, NSError * _Nullable))completion;
- (void)bridge_af_cancelImageRequest;
@end


@interface UIViewController (SWIFT_EXTENSION(SidestepSDK))
- (void)objcPresentBlurredViewController:(UIViewController * _Nonnull)controller;
@end


SWIFT_CLASS("_TtC11SidestepSDK17UpdateOrderParams")
@interface UpdateOrderParams : NSObject
- (NSDictionary<NSString *, id> * _Nullable)toDictionary;
- (void)setShowId:(NSNumber * _Nullable)value;
- (void)setUserId:(NSNumber * _Nullable)value;
- (void)setFirstName:(NSString * _Nullable)value;
- (void)setLastName:(NSString * _Nullable)value;
- (void)setEmail:(NSString * _Nullable)value;
- (void)setDeliveryMethod:(enum OrderDeliveryMethod)value;
- (void)setCardId:(NSNumber * _Nullable)value;
- (void)setStripeToken:(NSString * _Nullable)value;
- (void)setChargeToken:(NSString * _Nullable)value;
- (void)setReferrer:(NSString * _Nullable)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK4User")
@interface User : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, strong) NSNumber * _Nullable cardId;
@property (nonatomic, strong) Card * _Nullable card;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, strong) NSNumber * _Nullable isVendor;
@property (nonatomic, strong) NSNumber * _Nullable isAdmin;
@property (nonatomic, strong) NSOrderedSet * _Nullable orders;
+ (User * _Nullable)getUser:(NSString * _Nonnull)email;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocation;

SWIFT_CLASS("_TtC11SidestepSDK5Venue")
@interface Venue : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable venueId;
@property (nonatomic, strong) NSNumber * _Nullable stockId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable timeZoneName;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable region;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, strong) NSNumber * _Nullable latitude;
@property (nonatomic, strong) NSNumber * _Nullable longitude;
@property (nonatomic, readonly, copy) NSString * _Nonnull cityString;
@property (nonatomic, readonly, strong) CLLocation * _Nonnull location;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@interface FRCFactory (SWIFT_EXTENSION(SidestepSDK))
+ (NSFetchedResultsController<OrderItem *> * _Nonnull)createPickUpOrdersForOrdersController:(NSNumber * _Nonnull)userId delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<OrderItem *> * _Nonnull)createDeliveryOrdersForOrdersController:(NSNumber * _Nonnull)userId delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<Order *> * _Nonnull)createCartOrderForCartManager:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<Order *> * _Nonnull)createPlacedOrderForOrderCompletionController:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<Order *> * _Nonnull)createOrderMonitorForOrderConfirmationController:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<OrderItem *> * _Nonnull)createOrderItemsMonitorForOrderConfirmationController:(NSNumber * _Nullable)orderId delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<Order *> * _Nonnull)createOrderMonitorForCartTableViewManager:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<Order *> * _Nonnull)createOrderMonitorForCartController:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
+ (NSFetchedResultsController<OrderItem *> * _Nonnull)createOrderItemsMonitorForCartController:(NSNumber * _Nullable)orderId delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate;
@end

#pragma clang diagnostic pop
