// Generated by Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
@import CoreGraphics;
@import CoreData;
@import MBProgressHUD;
#endif

#import <SidestepSDK/SidestepSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class ErrorInfo;
@class NSHTTPURLResponse;

SWIFT_CLASS("_TtC11SidestepSDK10APIManager")
@interface APIManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) APIManager * _Nullable sharedManager;)
+ (APIManager * _Nullable)sharedManager SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedManager:(APIManager * _Nullable)value;
@property (nonatomic, copy) void (^ _Nullable connectivityErrorBlock)(void);
+ (void)setToken:(NSString * _Nonnull)token email:(NSString * _Nonnull)email;
+ (void)updateEmail:(NSString * _Nonnull)email;
+ (void)clearAuthHeader;
- (void)downloadData:(NSString * _Nonnull)path parameters:(NSDictionary<NSString *, id> * _Nullable)parameters success:(void (^ _Nullable)(NSData * _Nullable))success failure:(void (^ _Nullable)(ErrorInfo * _Nullable, NSHTTPURLResponse * _Nullable))failure;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
+ (void)getToken:(NSString * _Nonnull)email password:(NSString * _Nonnull)password success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nullable))success failure:(void (^ _Nullable)(ErrorInfo * _Nullable, NSHTTPURLResponse * _Nullable))failure;
+ (void)getToken:(NSString * _Nonnull)fbToken email:(NSString * _Nullable)email success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nullable))success failure:(void (^ _Nullable)(ErrorInfo * _Nullable, NSHTTPURLResponse * _Nullable))failure;
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
+ (BOOL)isStatusRequestIsInQueue SWIFT_WARN_UNUSED_RESULT;
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
@end

@class NSNumber;
@class NSManagedObject;

@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
+ (void (^ _Nullable)(ErrorInfo * _Nullable, NSHTTPURLResponse * _Nullable))bridgeFailureBlock:(FailureObjcBlock _Nullable)failure SWIFT_WARN_UNUSED_RESULT;
+ (void)getShows:(NSNumber * _Nonnull)artistId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)objcGetShowProductVariants:(NSArray<NSNumber *> * _Nonnull)showProductIds success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)objcGetShowProductsForShowWithId:(NSNumber * _Nonnull)showId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getArtists:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getOrders:(NSArray<NSNumber *> * _Nonnull)ids orderToken:(NSString * _Nullable)orderToken success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getOrders:(NSNumber * _Nonnull)userId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)updateDeliveryAddress:(NSNumber * _Nonnull)orderId cartOrderToken:(NSString * _Nullable)cartOrderToken addressInfo:(NSDictionary<NSString *, id> * _Nonnull)addressInfo success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)createDeliveryAddress:(NSNumber * _Nonnull)orderId cartOrderToken:(NSString * _Nullable)cartOrderToken addressInfo:(NSDictionary<NSString *, id> * _Nonnull)addressInfo success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)recoverPassword:(NSString * _Nonnull)email success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)placeOrder:(NSNumber * _Nonnull)orderId cardId:(NSNumber * _Nullable)cardId chargeToken:(NSString * _Nullable)chargeToken dateOfBirth:(NSDate * _Nullable)dateOfBirth success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getCurrentUser:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
+ (void)getCard:(NSNumber * _Nonnull)cardId success:(SuccessObjcBlock _Nullable)success failure:(FailureObjcBlock _Nullable)failure;
@end


@interface APIManager (SWIFT_EXTENSION(SidestepSDK))
+ (void)downloadPassbookFile:(NSNumber * _Nonnull)orderId orderToken:(NSString * _Nullable)orderToken success:(void (^ _Nullable)(NSData * _Nullable))success failure:(void (^ _Nullable)(ErrorInfo * _Nullable, NSHTTPURLResponse * _Nullable))failure;
+ (void)orderLookup:(NSNumber * _Nonnull)orderId showId:(NSNumber * _Nonnull)showId usingQRCodeReader:(BOOL)usingQRCodeReader;
@end


SWIFT_CLASS("_TtC11SidestepSDK19APIManagerConstants")
@interface APIManagerConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerFirstNameKey;)
+ (NSString * _Nonnull)kAPIManagerFirstNameKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerLastNameKey;)
+ (NSString * _Nonnull)kAPIManagerLastNameKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerAddress1Key;)
+ (NSString * _Nonnull)kAPIManagerAddress1Key SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerAddress2Key;)
+ (NSString * _Nonnull)kAPIManagerAddress2Key SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerCityKey;)
+ (NSString * _Nonnull)kAPIManagerCityKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerRegionKey;)
+ (NSString * _Nonnull)kAPIManagerRegionKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerZipKey;)
+ (NSString * _Nonnull)kAPIManagerZipKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerCountryKey;)
+ (NSString * _Nonnull)kAPIManagerCountryKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull kAPIManagerCountryCodeKey;)
+ (NSString * _Nonnull)kAPIManagerCountryCodeKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIVisualEffect;
@class NSCoder;

SWIFT_CLASS("_TtC11SidestepSDK10BluredView")
@interface BluredView : UIVisualEffectView
- (nonnull instancetype)initWithEffect:(UIVisualEffect * _Nullable)effect SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;

SWIFT_CLASS("_TtC11SidestepSDK18AbstractPickerView")
@interface AbstractPickerView : BluredView
@property (nonatomic, strong) IBOutlet UITableView * _Null_unspecified tableView;
+ (AbstractPickerView * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
- (void)showBottomButtonWithTitle:(NSString * _Nonnull)title target:(id _Nonnull)target action:(SEL _Nonnull)action;
@property (nonatomic, readonly) CGFloat bottomSectionHeight;
- (void)updateConstraints;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS("_TtC11SidestepSDK7Address")
@interface Address : NSManagedObject
@property (nonatomic, copy) NSString * _Nullable address1;
@property (nonatomic, copy) NSString * _Nullable address2;
@property (nonatomic, strong) NSNumber * _Nullable addressId;
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, copy) NSString * _Nullable region;
@property (nonatomic, copy) NSString * _Nullable zip;
@property (nonatomic, strong) NSSet * _Nullable orders;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Address (SWIFT_EXTENSION(SidestepSDK))
- (NSString * _Nonnull)addressString SWIFT_WARN_UNUSED_RESULT;
@end

@class UIAlertController;

SWIFT_CLASS("_TtC11SidestepSDK24AlertControllerPresenter")
@interface AlertControllerPresenter : NSObject
+ (void)presentAlert:(UIAlertController * _Nonnull)alertController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSOrderedSet;

SWIFT_CLASS("_TtC11SidestepSDK6Artist")
@interface Artist : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, strong) NSNumber * _Nullable isDeliveryAvailable;
@property (nonatomic, strong) NSNumber * _Nullable localAttributeIsArtistMissedInResponse;
@property (nonatomic, strong) NSNumber * _Nullable order;
@property (nonatomic, strong) NSNumber * _Nullable published;
@property (nonatomic, copy) NSString * _Nullable slug;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, strong) NSNumber * _Nullable stripeConnectionId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSOrderedSet * _Nullable advanceSheets;
@property (nonatomic, strong) NSOrderedSet * _Nullable artistEmployments;
@property (nonatomic, strong) NSOrderedSet * _Nullable orders;
@property (nonatomic, strong) NSOrderedSet * _Nullable products;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
@property (nonatomic, strong) NSOrderedSet * _Nullable tours;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Artist (SWIFT_EXTENSION(SidestepSDK))
@end

@class User;

SWIFT_CLASS("_TtC11SidestepSDK16ArtistEmployment")
@interface ArtistEmployment : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistEmploymentId;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable role;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) User * _Nullable user;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK21BluredModalController_")
@protocol BluredModalController
@property (nonatomic, readonly, strong) BluredView * _Nonnull bluredView;
@end


@class UIBarButtonItem;

SWIFT_CLASS("_TtC11SidestepSDK13ButtonBuilder")
@interface ButtonBuilder : NSObject
+ (UIBarButtonItem * _Nonnull)closeBarButtonItemWithTarget:(id _Nonnull)target selector:(SEL _Nonnull)selector SWIFT_WARN_UNUSED_RESULT;
+ (UIBarButtonItem * _Nonnull)backBarButtonItemWithTarget:(id _Nonnull)target selector:(SEL _Nonnull)selector SWIFT_WARN_UNUSED_RESULT;
+ (UIBarButtonItem * _Nonnull)menuBarButtonItemWithTarget:(id _Nonnull)target selector:(SEL _Nonnull)selector SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK4Card")
@interface Card : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable cardId;
@property (nonatomic, copy) NSString * _Nullable last4;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, strong) User * _Nullable user;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK13Configuration")
@interface Configuration : NSObject
+ (NSString * _Nonnull)baseUrl SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK15CoreDataManager")
@interface CoreDataManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) CoreDataManager * _Nullable shared;)
+ (CoreDataManager * _Nullable)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(CoreDataManager * _Nullable)value;
- (NSString * _Nonnull)getEntityNameFromClass:(Class _Nonnull)entityClass SWIFT_WARN_UNUSED_RESULT;
- (void)save;
- (void)deleteObject:(NSManagedObject * _Nonnull)object;
- (void)clearAllData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@protocol ErrorHandlerSupportWorker;

SWIFT_CLASS("_TtC11SidestepSDK12ErrorHandler")
@interface ErrorHandler : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ErrorHandler * _Nonnull sharedInstance;)
+ (ErrorHandler * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) id <ErrorHandlerSupportWorker> _Nullable suportWorker;
- (void)supportButtonTap:(NSString * _Nullable)subject;
- (void)displayError:(ErrorInfo * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK25ErrorHandlerSupportWorker_")
@protocol ErrorHandlerSupportWorker
- (BOOL)shouldAddSupportButton:(ErrorInfo * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (void)supportButtonTap:(NSString * _Nullable)subject;
@end


SWIFT_CLASS("_TtC11SidestepSDK9ErrorInfo")
@interface ErrorInfo : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable errors;
@property (nonatomic, readonly, copy) NSString * _Nullable error;
@property (nonatomic, readonly, copy) NSDate * _Nonnull datetime;
- (NSString * _Nullable)baseError SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@protocol NSFetchedResultsControllerDelegate;

SWIFT_CLASS("_TtC11SidestepSDK10FRCFactory")
@interface FRCFactory : NSObject
// 'createPickUpOrdersForOrdersController(_:delegate:)' below
// 'createDeliveryOrdersForOrdersController(_:delegate:)' below
// 'createCartOrderForCartManager(_:)' below
// 'createPlacedOrderForOrderCompletionController(_:)' below
// 'createOrderMonitorForCartTableViewManager(_:)' below
+ (NSFetchedResultsController<Artist *> * _Nullable)createPublishedArtistsMonitorForArtistsControllerWithFilerByArtistIds:(NSArray<NSNumber *> * _Nullable)filerByArtistIds delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SSCheckoutFlowProtocol;

SWIFT_CLASS("_TtC11SidestepSDK22FlowControllerSettings")
@interface FlowControllerSettings : NSObject
@property (nonatomic, readonly) BOOL showStep;
@property (nonatomic, readonly, copy) id <SSCheckoutFlowProtocol> _Nonnull (^ _Nonnull builderBlock)(void);
- (nonnull instancetype)initWithBuilderBlock:(id <SSCheckoutFlowProtocol> _Nonnull (^ _Nonnull)(void))builderBlock showStep:(BOOL)showStep OBJC_DESIGNATED_INITIALIZER;
+ (FlowControllerSettings * _Nonnull)create:(id <SSCheckoutFlowProtocol> _Nonnull (^ _Nonnull)(void))builderBlock showStep:(BOOL)showStep SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class NSDateFormatter;

SWIFT_CLASS("_TtC11SidestepSDK9Formatter")
@interface Formatter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDateFormatter * _Nonnull jsonDateFormatter;)
+ (NSDateFormatter * _Nonnull)jsonDateFormatter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSDateFormatter * _Nonnull jsonDateTimeFormatter;)
+ (NSDateFormatter * _Nonnull)jsonDateTimeFormatter SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum LoggerMode : NSInteger;

SWIFT_CLASS("_TtC11SidestepSDK6Logger")
@interface Logger : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) Logger * _Nonnull shared;)
+ (Logger * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(Logger * _Nonnull)value;
@property (nonatomic) enum LoggerMode mode;
- (void)logError:(NSString * _Nullable)message;
- (void)logMessage:(NSString * _Nullable)message;
+ (void)logError:(NSString * _Nullable)message;
+ (void)logMessage:(NSString * _Nullable)message;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, LoggerMode) {
  LoggerModeNone = 0,
  LoggerModeErrors = 1,
  LoggerModeAllOneLine = 2,
  LoggerModeAll = 3,
};


@interface MBProgressHUD (SWIFT_EXTENSION(SidestepSDK))
@end


SWIFT_CLASS("_TtC11SidestepSDK7Mapping")
@interface Mapping : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK8MetaData")
@interface MetaData : NSObject
@property (nonatomic, strong) NSNumber * _Nullable totalPages;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface NSManagedObject (SWIFT_EXTENSION(SidestepSDK))
@end


@interface NSObject (SWIFT_EXTENSION(SidestepSDK))
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK18NavigationDelegate_")
@protocol NavigationDelegate <NSObject>
- (void)showCart;
- (void)showHomeController;
@end


SWIFT_CLASS("_TtC11SidestepSDK13NoArtistsView")
@interface NoArtistsView : UIView
+ (NoArtistsView * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK22NumberArrayTransformer")
@interface NumberArrayTransformer : NSValueTransformer
+ (Class _Nonnull)transformedValueClass SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)allowsReverseTransformation SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)transformedValue:(id _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)reverseTransformedValue:(id _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Show;

SWIFT_CLASS("_TtC11SidestepSDK5Order")
@interface Order : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable additionalFeeInCents;
@property (nonatomic, strong) NSNumber * _Nullable applicationFee;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable chargePaymentSystem;
@property (nonatomic, copy) NSString * _Nullable chargeToken;
@property (nonatomic, copy) NSString * _Nullable confirmationCode;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, strong) NSNumber * _Nullable createdByUserId;
@property (nonatomic, copy) NSString * _Nullable createdInSidestepAppIdentifier;
@property (nonatomic, copy) NSString * _Nullable deliveryMethod;
@property (nonatomic, strong) NSNumber * _Nullable deliveryState;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, strong) NSNumber * _Nullable fee;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, strong) NSNumber * _Nullable orderId;
@property (nonatomic) id _Nullable orderItemIds;
@property (nonatomic, copy) NSString * _Nullable orderTextStatus;
@property (nonatomic, copy) NSString * _Nullable orderToken;
@property (nonatomic, copy) NSString * _Nullable referrer;
@property (nonatomic, strong) NSNumber * _Nullable refundableNum;
@property (nonatomic, strong) NSNumber * _Nullable refundedAmount;
@property (nonatomic, copy) NSDate * _Nullable refundedAt;
@property (nonatomic, copy) NSString * _Nullable refundState;
@property (nonatomic, strong) NSNumber * _Nullable requiresDateOfBirthNumber;
@property (nonatomic, strong) NSNumber * _Nullable shippingAddressId;
@property (nonatomic, strong) NSNumber * _Nullable shippingFee;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, strong) NSNumber * _Nullable subtotal;
@property (nonatomic, strong) NSNumber * _Nullable total;
@property (nonatomic, copy) NSString * _Nullable trackingCode;
@property (nonatomic, copy) NSString * _Nullable trackingUrl;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, strong) NSNumber * _Nullable isPhoneConfirmed;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) NSOrderedSet * _Nullable conversions;
@property (nonatomic, strong) NSOrderedSet * _Nullable conversionsForConverdedOrder;
@property (nonatomic, strong) User * _Nullable createdByUser;
@property (nonatomic, strong) NSOrderedSet * _Nullable orderItems;
@property (nonatomic, strong) NSOrderedSet * _Nullable refunds;
@property (nonatomic, strong) Address * _Nullable shippingAddress;
@property (nonatomic, strong) Show * _Nullable show;
@property (nonatomic, strong) User * _Nullable user;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Order (SWIFT_EXTENSION(SidestepSDK))
+ (NSArray<Order *> * _Nullable)getCartOrders SWIFT_WARN_UNUSED_RESULT;
+ (Order * _Nullable)getOrder:(NSString * _Nullable)orderToken SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isPickupOrder;
@property (nonatomic, readonly) BOOL isDeliveryOrder;
@property (nonatomic, readonly) BOOL isCartOrder;
@property (nonatomic, readonly) BOOL isRefunded;
@property (nonatomic, readonly) BOOL isAllItemsAvailable;
- (void)unlinkShowAndSave;
@end

@class ProductVariant;

SWIFT_CLASS("_TtC11SidestepSDK15OrderCartWorker")
@interface OrderCartWorker : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull OrderCartWorkerOrderChanged;)
+ (NSNotificationName _Nonnull)OrderCartWorkerOrderChanged SWIFT_WARN_UNUSED_RESULT;
- (void)addOrderItemToCartForDelivery:(ProductVariant * _Nonnull)productVariant;
- (void)addOrderItemToCartForPickUp:(ProductVariant * _Nonnull)productVariant show:(Show * _Nonnull)show;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, OrderDeliveryMethod) {
  OrderDeliveryMethodPickup = 0,
  OrderDeliveryMethodShipToAddress = 1,
  OrderDeliveryMethodNotDefined = 2,
};


SWIFT_CLASS("_TtC11SidestepSDK9OrderItem")
@interface OrderItem : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable applicationFee;
@property (nonatomic, copy) NSString * _Nullable artistTitle;
@property (nonatomic, strong) NSNumber * _Nullable available;
@property (nonatomic, strong) NSNumber * _Nullable fee;
@property (nonatomic, strong) NSNumber * _Nullable orderId;
@property (nonatomic, strong) NSNumber * _Nullable orderItemId;
@property (nonatomic, strong) NSNumber * _Nullable price;
@property (nonatomic, copy) NSString * _Nullable priceType;
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, strong) NSNumber * _Nullable quantity;
@property (nonatomic, strong) NSNumber * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSOrderedSet * _Nullable conversionItems;
@property (nonatomic, strong) Order * _Nullable order;
@property (nonatomic, strong) ProductVariant * _Nullable productVariant;
@property (nonatomic, strong) NSOrderedSet * _Nullable refundItems;
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable refundedState;
@property (nonatomic, strong) NSNumber * _Nullable refundedQuantity;
@property (nonatomic) id _Nullable canBePickedUpAtShowWithIds;
@property (nonatomic, strong) NSOrderedSet * _Nullable canBePickedUpAtShows;
@property (nonatomic, strong) NSNumber * _Nullable canBeShippedToAddress;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSPredicate;

@interface OrderItem (SWIFT_EXTENSION(SidestepSDK))
+ (NSPredicate * _Nonnull)orphanedOrderItemsOrInCartPredicate SWIFT_WARN_UNUSED_RESULT;
@end


@interface OrderItem (SWIFT_EXTENSION(SidestepSDK))
+ (OrderItem * _Nullable)getOrderItem:(NSNumber * _Nonnull)orderItemId SWIFT_WARN_UNUSED_RESULT;
@end


@interface OrderItem (SWIFT_EXTENSION(SidestepSDK))
@end

typedef SWIFT_ENUM(NSInteger, OrderPaySystem) {
  OrderPaySystemStripe = 0,
  OrderPaySystemCardFlightSwipeToken = 1,
  OrderPaySystemCardFlightEMV = 2,
};

@class UINib;

SWIFT_CLASS("_TtC11SidestepSDK18OtherProductCVCell")
@interface OtherProductCVCell : UICollectionViewCell
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull reuseId;)
+ (NSString * _Nonnull)reuseId SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UINib * _Nonnull nib;)
+ (UINib * _Nonnull)nib SWIFT_WARN_UNUSED_RESULT;
- (void)awakeFromNib;
- (void)prepareForReuse;
- (void)setImageUrl:(NSURL * _Nullable)imageUrl price:(NSString * _Nullable)price;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK14PickupLocation")
@interface PickupLocation : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable pickupLocationId;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable html;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, strong) Show * _Nullable show;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class Tour;

SWIFT_CLASS("_TtC11SidestepSDK7Product")
@interface Product : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, strong) NSNumber * _Nullable availableForDelivery;
@property (nonatomic, strong) NSNumber * _Nullable availableForPickup;
@property (nonatomic, strong) NSNumber * _Nullable canBeShippedToAddress;
@property (nonatomic) id _Nullable canBePickedUpAtShowWithIds;
@property (nonatomic, strong) NSNumber * _Nullable exclusive;
@property (nonatomic, strong) NSNumber * _Nullable localAttributeIsProductMissedInResponse;
@property (nonatomic, strong) NSNumber * _Nullable price;
@property (nonatomic, strong) NSNumber * _Nullable productDeleted;
@property (nonatomic, copy) NSString * _Nullable productDescription;
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable promoImage;
@property (nonatomic, strong) NSNumber * _Nullable published;
@property (nonatomic, strong) NSNumber * _Nullable sortOrder;
@property (nonatomic, copy) NSString * _Nullable squareImage;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSNumber * _Nullable tourId;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) NSOrderedSet * _Nullable productVariants;
@property (nonatomic, strong) NSOrderedSet * _Nullable showProducts;
@property (nonatomic, strong) Tour * _Nullable tour;
@property (nonatomic, strong) NSOrderedSet * _Nullable canBePickedUpAtShows;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Product (SWIFT_EXTENSION(SidestepSDK))
@end

@protocol ProductDetailsControllerDelegate;
@class UITableViewCell;
@class NSBundle;

SWIFT_CLASS("_TtC11SidestepSDK24ProductDetailsController")
@interface ProductDetailsController : UIViewController <ProductDetailsOtherProductsCellDelegate, UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) id <ProductDetailsControllerDelegate> _Nullable delegate;
@property (nonatomic, strong) ProductVariant * _Nullable selectedVariant;
@property (nonatomic, readonly) BOOL showSizesForDelivery;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)didSelectProduct:(Product * _Null_unspecified)product;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_PROTOCOL("_TtP11SidestepSDK32ProductDetailsControllerDelegate_")
@protocol ProductDetailsControllerDelegate <NSObject>
- (void)didSelectProductFromOtherItems:(Product * _Nonnull)product;
- (void)productDetailsControllerItemAdded;
- (void)productDetailsControllerNeedsToGoToCart;
@end

@class SSSize;

SWIFT_CLASS("_TtC11SidestepSDK14ProductVariant")
@interface ProductVariant : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable enabled;
@property (nonatomic, strong) NSNumber * _Nullable price;
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, strong) NSNumber * _Nullable sizeId;
@property (nonatomic, copy) NSString * _Nullable sku;
@property (nonatomic, strong) NSNumber * _Nullable canBeShippedToAddress;
@property (nonatomic) id _Nullable canBePickedUpAtShowWithIds;
@property (nonatomic, strong) NSNumber * _Nullable localAttributeIsProductMissedInResponse;
@property (nonatomic, strong) NSOrderedSet * _Nullable orderItems;
@property (nonatomic, strong) Product * _Nullable product;
@property (nonatomic, strong) NSOrderedSet * _Nullable showProductVariants;
@property (nonatomic, strong) SSSize * _Nullable size;
@property (nonatomic, strong) NSOrderedSet * _Nullable canBePickedUpAtShows;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK18ProductsController")
@interface ProductsController : UIViewController <NSFetchedResultsControllerDelegate, ProductDetailsControllerDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
@property (nonatomic, readonly, copy) NSString * _Nullable currency;
@property (nonatomic, readonly) BOOL showFiltersControl;
- (void)controllerDidChangeContent:(NSFetchedResultsController<id <NSFetchRequestResult>> * _Nonnull)controller;
- (void)didSelectProductFromOtherItems:(Product * _Nonnull)product;
- (void)productDetailsControllerItemAdded;
- (void)productDetailsControllerNeedsToGoToCart;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface ProductsController (SWIFT_EXTENSION(SidestepSDK))
+ (void)preloadAvailableShowsForAtristId:(NSNumber * _Nonnull)artistId success:(void (^ _Nonnull)(void))success failureObjc:(FailureObjcBlock _Nullable)failureObjc;
@end

@class UIImage;

SWIFT_CLASS("_TtC11SidestepSDK15QRCodeGenerator")
@interface QRCodeGenerator : NSObject
+ (UIImage * _Nullable)generateQRCodeFromString:(NSString * _Nonnull)string size:(CGFloat)size SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK9Recipient")
@interface Recipient : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable recipientId;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, copy) NSString * _Nullable contact;
@property (nonatomic, copy) NSString * _Nullable contactMethod;
@property (nonatomic, strong) NSOrderedSet * _Nullable userNotifications;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK6Refund")
@interface Refund : NSManagedObject
@property (nonatomic, copy) NSDate * _Nullable appliedAt;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, strong) NSNumber * _Nullable isAppliedNum;
@property (nonatomic, strong) NSNumber * _Nullable itemsFee;
@property (nonatomic, strong) NSNumber * _Nullable itemsTotal;
@property (nonatomic, strong) NSNumber * _Nullable minimumFee;
@property (nonatomic, strong) NSNumber * _Nullable orderId;
@property (nonatomic, strong) NSNumber * _Nullable refundId;
@property (nonatomic, strong) NSNumber * _Nullable shippingFee;
@property (nonatomic, strong) NSNumber * _Nullable totalAmount;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) Order * _Nullable order;
@property (nonatomic, strong) NSOrderedSet * _Nullable refundItems;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK10RefundItem")
@interface RefundItem : NSManagedObject
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, strong) NSNumber * _Nullable orderItemId;
@property (nonatomic, strong) NSNumber * _Nullable price;
@property (nonatomic, strong) NSNumber * _Nullable quantity;
@property (nonatomic, strong) NSNumber * _Nullable refundId;
@property (nonatomic, strong) NSNumber * _Nullable refundItemId;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) OrderItem * _Nullable orderItem;
@property (nonatomic, strong) Refund * _Nullable refund;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK19SSCurrencyFormatter")
@interface SSCurrencyFormatter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) SSCurrencyFormatter * _Nonnull sharedInstance;)
+ (SSCurrencyFormatter * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
+ (void)setSharedInstance:(SSCurrencyFormatter * _Nonnull)value;
- (NSString * _Nullable)stringFromNumber:(NSNumber * _Nullable)number currencyFormat:(NSString * _Nullable)currencyFormat SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK6SSSize")
@interface SSSize : NSManagedObject
@property (nonatomic, copy) NSString * _Nullable code;
@property (nonatomic, strong) NSNumber * _Nullable order;
@property (nonatomic, strong) NSNumber * _Nullable sizeId;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSOrderedSet * _Nullable productVariants;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface SSSize (SWIFT_EXTENSION(SidestepSDK))
@property (nonatomic, readonly) BOOL isOneSizeOrNoSize;
@end


SWIFT_CLASS("_TtC11SidestepSDK10SalesEntry")
@interface SalesEntry : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable artistImage;
@property (nonatomic, copy) NSString * _Nullable artistTitle;
@property (nonatomic, strong) NSNumber * _Nullable grossCompleted;
@property (nonatomic, strong) NSNumber * _Nullable grossPlaced;
@property (nonatomic, strong) NSNumber * _Nullable grossTotal;
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable productImage;
@property (nonatomic, copy) NSString * _Nullable productTitle;
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, strong) NSNumber * _Nullable quantityCompleted;
@property (nonatomic, strong) NSNumber * _Nullable quantityPlaced;
@property (nonatomic, strong) NSNumber * _Nullable quantityTotal;
@property (nonatomic, strong) NSNumber * _Nullable salesEntryId;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, copy) NSString * _Nullable sizeCode;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class ShowGroup;
@class Venue;

SWIFT_CLASS("_TtC11SidestepSDK4Show")
@interface Show : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable acceptsNewOrders;
@property (nonatomic, strong) NSNumber * _Nullable allowRefunds;
@property (nonatomic) id _Nullable artistIds;
@property (nonatomic, copy) NSDate * _Nullable availableFrom;
@property (nonatomic, copy) NSDate * _Nullable availableUntil;
@property (nonatomic, strong) NSNumber * _Nullable canPlaceOrders;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, strong) NSNumber * _Nullable hidden;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, copy) NSString * _Nullable pickupLocationLinkValue;
@property (nonatomic, copy) NSDate * _Nullable showDatetime;
@property (nonatomic, strong) NSNumber * _Nullable showGroupId;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic) id _Nullable tourIds;
@property (nonatomic, strong) NSNumber * _Nullable venueId;
@property (nonatomic, strong) NSOrderedSet * _Nullable advanceSheets;
@property (nonatomic, strong) NSOrderedSet * _Nullable artists;
@property (nonatomic, strong) NSOrderedSet * _Nullable orders;
@property (nonatomic, strong) PickupLocation * _Nullable pickupLocation;
@property (nonatomic, strong) ShowGroup * _Nullable showGroup;
@property (nonatomic, strong) NSOrderedSet * _Nullable showProducts;
@property (nonatomic, strong) NSOrderedSet * _Nullable tours;
@property (nonatomic, strong) Venue * _Nullable venue;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Show (SWIFT_EXTENSION(SidestepSDK))
+ (Show * _Nullable)showWithId:(NSNumber * _Nonnull)showId SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<Show *> * _Nullable)servicedShows SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<Show *> * _Nullable)servicedShows:(NSArray<NSNumber *> * _Nonnull)artistIds SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isScheduled;
@property (nonatomic, readonly) BOOL isRunning;
@property (nonatomic, readonly) BOOL isFinished;
@property (nonatomic, readonly) BOOL isCancelled;
@property (nonatomic, readonly, copy) NSDateComponents * _Nullable localDateComponents;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateString;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateStringLongStyle;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateStringShortStyle;
@property (nonatomic, readonly, copy) NSString * _Nullable localDateTimeString;
@end


SWIFT_CLASS("_TtC11SidestepSDK9ShowGroup")
@interface ShowGroup : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable showGroupId;
@property (nonatomic) id _Nullable showIds;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK11ShowProduct")
@interface ShowProduct : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable availableForOrdering;
@property (nonatomic, strong) NSNumber * _Nullable productId;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, strong) NSNumber * _Nullable showProductId;
@property (nonatomic, strong) Product * _Nullable product;
@property (nonatomic, strong) Show * _Nullable show;
@property (nonatomic, strong) NSSet * _Nullable showProductVariants;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShowProduct (SWIFT_EXTENSION(SidestepSDK))
+ (ShowProduct * _Nullable)getShowProduct:(NSNumber * _Nonnull)showProductId SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<ShowProduct *> * _Nullable)getShowProducts:(NSArray<NSNumber *> * _Nonnull)productIds showId:(NSNumber * _Nonnull)showId SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11SidestepSDK18ShowProductVariant")
@interface ShowProductVariant : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable available;
@property (nonatomic, strong) NSNumber * _Nullable availableQuantity;
@property (nonatomic, strong) NSNumber * _Nullable canBeOrdered;
@property (nonatomic, strong) NSNumber * _Nullable limit;
@property (nonatomic, strong) NSNumber * _Nullable productVariantId;
@property (nonatomic, strong) NSNumber * _Nullable shouldCheckAvailableQuantity;
@property (nonatomic, strong) NSNumber * _Nullable showProductId;
@property (nonatomic, strong) NSNumber * _Nullable showProductVariantId;
@property (nonatomic, strong) ProductVariant * _Nullable productVariant;
@property (nonatomic, strong) ShowProduct * _Nullable showProduct;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShowProductVariant (SWIFT_EXTENSION(SidestepSDK))
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariants:(NSNumber * _Nonnull)showProductId SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariants:(NSNumber * _Nonnull)showId productId:(NSNumber * _Nonnull)productId SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariantsSortedBySize:(NSNumber * _Nonnull)showId productVariantIds:(NSArray<NSNumber *> * _Nonnull)productVariantIds SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<ShowProductVariant *> * _Nullable)getShowProductVariantsSortedBySize:(NSNumber * _Nonnull)showId productId:(NSNumber * _Nonnull)productId SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isAvailable;
@property (nonatomic, readonly) BOOL isCanBeOrderd;
@property (nonatomic, readonly) BOOL isShouldCheckAvailableQuantity;
@end

@class UINavigationController;

SWIFT_CLASS("_TtC11SidestepSDK11SidestepSDK")
@interface SidestepSDK : NSObject
@property (nonatomic, copy) void (^ _Nullable closeBlock)(void);
@property (nonatomic, readonly, strong) UINavigationController * _Nullable navigationController;
- (void)needToPopController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC11SidestepSDK14SidestepShared")
@interface SidestepShared : NSObject
+ (void)setupWithBaseUrl:(NSString * _Nonnull)baseUrl httpHeaders:(NSDictionary<NSString *, NSString *> * _Nonnull)httpHeaders databaseFileName:(NSString * _Nonnull)databaseFileName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK4Tour")
@interface Tour : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, copy) NSString * _Nullable state;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable displayTitle;
@property (nonatomic, strong) NSNumber * _Nullable tourId;
@property (nonatomic, strong) NSNumber * _Nullable localAttributeIsProductMissedInResponse;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) NSOrderedSet * _Nullable products;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface Tour (SWIFT_EXTENSION(SidestepSDK))
@end


@interface UIAlertController (SWIFT_EXTENSION(SidestepSDK))
- (nonnull instancetype)initWithOkButtonAndMessage:(NSString * _Nullable)message;
- (nonnull instancetype)initWithOkButtonAndTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message;
- (nonnull instancetype)initWithOkButtonAndTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message okHandler:(void (^ _Nullable)(void))okHandler;
@end


@interface UIButton (SWIFT_EXTENSION(SidestepSDK))
@end


@interface UIButton (SWIFT_EXTENSION(SidestepSDK))
@end


@interface UIFont (SWIFT_EXTENSION(SidestepSDK))
@end


@interface UIImageView (SWIFT_EXTENSION(SidestepSDK))
- (void)bridge_af_setImageWithURL:(NSURL * _Nonnull)url;
- (void)bridge_af_setImageWithURL:(NSURL * _Nonnull)url completion:(void (^ _Nullable)(UIImage * _Nullable, NSError * _Nullable))completion;
- (void)bridge_af_cancelImageRequest;
@end


@interface UILabel (SWIFT_EXTENSION(SidestepSDK))
@end


@interface UITableView (SWIFT_EXTENSION(SidestepSDK))
@end


@interface UIViewController (SWIFT_EXTENSION(SidestepSDK))
@end


SWIFT_CLASS("_TtC11SidestepSDK17UpdateOrderParams")
@interface UpdateOrderParams : NSObject
- (NSDictionary<NSString *, id> * _Nullable)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (void)setOrderId:(NSNumber * _Nullable)value;
- (void)setShowId:(NSNumber * _Nullable)value;
- (void)setUserId:(NSNumber * _Nullable)value;
- (void)setFirstName:(NSString * _Nullable)value;
- (void)setLastName:(NSString * _Nullable)value;
- (void)setEmail:(NSString * _Nullable)value;
- (void)setDeliveryMethod:(enum OrderDeliveryMethod)value;
- (void)setCardId:(NSNumber * _Nullable)value;
- (void)setStripeToken:(NSString * _Nullable)value;
- (void)setChargeToken:(NSString * _Nullable)value;
- (void)setPaymentSystem:(enum OrderPaySystem)paymentSystem;
- (void)setCardFlightChargeDate:(NSDate * _Nullable)value;
- (void)setCardFlightMetadata:(NSString * _Nullable)value;
- (void)setCardFlightChargeId:(NSString * _Nullable)value;
- (void)setCardFlightLast4:(NSString * _Nullable)value;
- (void)setCardFlightCardID:(NSString * _Nullable)value;
- (void)setCardFlightChargeAmount:(NSNumber * _Nullable)value;
- (void)setReferrer:(NSString * _Nullable)value;
- (void)setPhone:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK4User")
@interface User : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable cardId;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable firstName;
@property (nonatomic, strong) NSNumber * _Nullable isAdmin;
@property (nonatomic, strong) NSNumber * _Nullable isVendor;
@property (nonatomic, copy) NSString * _Nullable lastName;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, strong) NSOrderedSet * _Nullable artistEmployments;
@property (nonatomic, strong) NSOrderedSet * _Nullable creatorForOrders;
@property (nonatomic, strong) Card * _Nullable card;
@property (nonatomic, strong) NSOrderedSet * _Nullable orders;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface User (SWIFT_EXTENSION(SidestepSDK))
+ (User * _Nullable)getUser:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC11SidestepSDK16UserNotification")
@interface UserNotification : NSManagedObject
@property (nonatomic, strong) NSNumber * _Nullable artistId;
@property (nonatomic, copy) NSDate * _Nullable createdAt;
@property (nonatomic, copy) NSString * _Nullable message;
@property (nonatomic, strong) NSNumber * _Nullable notificationId;
@property (nonatomic, strong) NSNumber * _Nullable recipientCount;
@property (nonatomic, copy) NSString * _Nullable recipientFilter;
@property (nonatomic) id _Nullable recipientIds;
@property (nonatomic, strong) NSNumber * _Nullable showId;
@property (nonatomic, copy) NSDate * _Nullable updatedAt;
@property (nonatomic, strong) NSNumber * _Nullable userId;
@property (nonatomic, strong) Artist * _Nullable artist;
@property (nonatomic, strong) NSOrderedSet * _Nullable recipients;
@property (nonatomic, strong) Show * _Nullable show;
@property (nonatomic, strong) User * _Nullable user;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11SidestepSDK5Venue")
@interface Venue : NSManagedObject
@property (nonatomic, copy) NSString * _Nullable city;
@property (nonatomic, copy) NSString * _Nullable country;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
@property (nonatomic, strong) NSNumber * _Nullable latitude;
@property (nonatomic, strong) NSNumber * _Nullable longitude;
@property (nonatomic, copy) NSString * _Nullable region;
@property (nonatomic, strong) NSNumber * _Nullable stockId;
@property (nonatomic, copy) NSString * _Nullable timeZoneName;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, strong) NSNumber * _Nullable venueId;
@property (nonatomic, strong) NSOrderedSet * _Nullable shows;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable keyPath;)
+ (NSString * _Nullable)keyPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocation;

@interface Venue (SWIFT_EXTENSION(SidestepSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull cityString;
@property (nonatomic, readonly, strong) CLLocation * _Nonnull location;
@end

@interface FRCFactory (SWIFT_EXTENSION(SidestepSDK))
+ (NSFetchedResultsController<OrderItem *> * _Nullable)createPickUpOrdersForOrdersController:(NSNumber * _Nonnull)userId delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (NSFetchedResultsController<OrderItem *> * _Nullable)createDeliveryOrdersForOrdersController:(NSNumber * _Nonnull)userId delegate:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (NSFetchedResultsController<Order *> * _Nullable)createCartOrderForCartManager:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (NSFetchedResultsController<Order *> * _Nullable)createPlacedOrderForOrderCompletionController:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (NSFetchedResultsController<Order *> * _Nullable)createOrderMonitorForCartTableViewManager:(id <NSFetchedResultsControllerDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
@end

#pragma clang diagnostic pop
